import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { useCounter } from "../hooks/useCounter.hook";
import { useCount } from "../hooks/useCount.hook";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { counter, signerCounter } = useCounter();
  const { count, setCount, isLoading, error } = useCount(counter);

  async function incrementCount() {
    try {
      // Execute the transaction that writes to the blockchain:
      // We use "signerCounter" contract here because the "signer" is
      // the actor that is "signing" or ultimately issuing the transaction.
      const transaction = await signerCounter?.increment();

      // Wait for the async blockchain write transaction to finish.
      await transaction.wait();

      // We use "counter" here to read the updated count value.
      // We dont need to use the "signerCounter" because we are not
      // updating or transacting againt the blcokchain.
      // Reading is a synchronous operation so we dont need to call ".wait()".
      const countResponse = await counter?.getCount();

      // update the count state
      setCount(countResponse.toNumber());
    } catch (err) {
      console.log(
        "Error: Counter Contract Could not write to blockchain ",
        err
      );
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Counter Contract</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Counter Smart Contract</h1>
        <h2 className={styles.secondary}>
          {isLoading ? null : `Count: ${count}`}
        </h2>
        <button className={styles.button} onClick={incrementCount}>
          Increment
        </button>
      </main>
      {error ? <p>{JSON.stringify(error)}</p> : null}
      <footer>
        <ul className={styles.footer}>
          <li className={styles.tech}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </li>
          <li className={styles.tech}>Ethers.js</li> |
          <li className={styles.tech}>Hardhat</li> |
          <li className={styles.tech}>Ethereum</li> |
          <li className={styles.tech}>react-query</li>
        </ul>
      </footer>
    </div>
  );
};

export default Home;
